// Generated by lab/re/presets27_export.py; do not edit. Indices of the parameter vector of a material (the values
// the system's tuning code resolves for a shape), in the order of the preset table's rows. Lengths are points,
// angles radians; DARK_OFFSET and DARK_HEIGHT are device pixels.

/** backdropScale */
export const P_SCALE = 0;
/** blur.radius */
export const P_BLUR = 1;
/** blur.opacities[0] */
export const P_BLUR_OP0 = 2;
/** blur.opacities[1] */
export const P_BLUR_OP1 = 3;
/** blur.opacities[2] */
export const P_BLUR_OP2 = 4;
/** blur.opacities[3] */
export const P_BLUR_OP3 = 5;
/** blur.distances[0] */
export const P_BLUR_D0 = 6;
/** blur.distances[1] */
export const P_BLUR_D1 = 7;
/** blur.distances[2] */
export const P_BLUR_D2 = 8;
/** blur.distances[3] */
export const P_BLUR_D3 = 9;
/** blurFill.blurRadius */
export const P_FILL_BLUR = 10;
/** blurFill.darkenOpacity */
export const P_FILL_DARKEN = 11;
/** blurFill.lightenOpacity */
export const P_FILL_LIGHTEN = 12;
/** blurFill.normalOpacity */
export const P_FILL_NORMAL = 13;
/** refraction.innerAmount */
export const P_IN_AMOUNT = 14;
/** refraction.innerHeight */
export const P_IN_HEIGHT = 15;
/** refraction.outerAmount */
export const P_OUT_AMOUNT = 16;
/** refraction.outerHeight */
export const P_OUT_HEIGHT = 17;
/** refraction.outerOpacity */
export const P_OUT_OPACITY = 18;
/** refraction.outerDistances[0] */
export const P_OUT_D0 = 19;
/** refraction.outerDistances[1] */
export const P_OUT_D1 = 20;
/** faceEffects.opacity */
export const P_FACE_OPACITY = 21;
/** faceEffects.ycc.white */
export const P_FACE_WHITE = 22;
/** faceEffects.ycc.black */
export const P_FACE_BLACK = 23;
/** faceEffects.ycc.saturation */
export const P_FACE_SAT = 24;
/** faceEffects.ycc.normalFill r */
export const P_FACE_FILL_R = 25;
/** faceEffects.ycc.normalFill g */
export const P_FACE_FILL_G = 26;
/** faceEffects.ycc.normalFill b */
export const P_FACE_FILL_B = 27;
/** faceEffects.ycc.normalFill a */
export const P_FACE_FILL_A = 28;
/** faceEffects.maxLuminance */
export const P_FACE_LUMA = 29;
/** faceEffects.maxLuminanceSDR */
export const P_FACE_LUMA_SDR = 30;
/** edgeBleed.amount */
export const P_BLEED_AMOUNT = 31;
/** edgeBleed.height */
export const P_BLEED_HEIGHT = 32;
/** edgeBleed.blurRadius */
export const P_BLEED_BLUR = 33;
/** edgeBleed.opacity */
export const P_BLEED_OPACITY = 34;
/** edgeBleed.distances[0] */
export const P_BLEED_D0 = 35;
/** edgeBleed.distances[1] */
export const P_BLEED_D1 = 36;
/** edgeBleed.useDarkenBlending */
export const P_BLEED_DARKEN = 37;
/** edgeBleed.ycc.white */
export const P_BLEED_WHITE = 38;
/** edgeBleed.ycc.black */
export const P_BLEED_BLACK = 39;
/** edgeBleed.ycc.saturation */
export const P_BLEED_SAT = 40;
/** shadow.opacity */
export const P_SHADOW_OPACITY = 41;
/** shadow.shadowRadius */
export const P_SHADOW_RADIUS = 42;
/** shadow.offset[0] */
export const P_SHADOW_X = 43;
/** shadow.offset[1] */
export const P_SHADOW_Y = 44;
/** shadow.amount */
export const P_SHADOW_AMOUNT = 45;
/** shadow.height */
export const P_SHADOW_HEIGHT = 46;
/** shadow.inset */
export const P_SHADOW_INSET = 47;
/** shadow.blurRadius */
export const P_SHADOW_BLUR = 48;
/** shadow.vibrancyContribution */
export const P_SHADOW_VIBRANCY = 49;
/** shadow.ycc.white */
export const P_SHADOW_WHITE = 50;
/** shadow.ycc.black */
export const P_SHADOW_BLACK = 51;
/** shadow.ycc.saturation */
export const P_SHADOW_SAT = 52;
/** shadow.ycc.normalFill r */
export const P_SHADOW_FILL_R = 53;
/** shadow.ycc.normalFill g */
export const P_SHADOW_FILL_G = 54;
/** shadow.ycc.normalFill b */
export const P_SHADOW_FILL_B = 55;
/** shadow.ycc.normalFill a */
export const P_SHADOW_FILL_A = 56;
/** ringShadow.opacity */
export const P_RING_OPACITY = 57;
/** ringShadow.blurRadius */
export const P_RING_BLUR = 58;
/** ringShadow.strokeWidth */
export const P_RING_WIDTH = 59;
/** ringShadow.verticalOffset */
export const P_RING_OFFSET = 60;
/** ringShadow.maskAmount */
export const P_RING_MASK = 61;
/** darkSpecular.amount */
export const P_DARK_AMOUNT = 62;
/** darkSpecular.angle (radians) */
export const P_DARK_ANGLE = 63;
/** darkSpecular.colorBias */
export const P_DARK_BIAS = 64;
/** darkSpecular.effectOffset */
export const P_DARK_OFFSET = 65;
/** darkSpecular.height */
export const P_DARK_HEIGHT = 66;
/** darkSpecular.spread (radians) */
export const P_DARK_SPREAD = 67;
/** darkSpecular.spreadSDR (radians) */
export const P_DARK_SPREAD_SDR = 68;
/** highlights.key.amount */
export const P_KEY_AMOUNT = 69;
/** highlights.key.curvature */
export const P_KEY_CURVATURE = 70;
/** highlights.key.height */
export const P_KEY_HEIGHT = 71;
/** highlights.key.opacity */
export const P_KEY_OPACITY = 72;
/** highlights.key.spread (radians) */
export const P_KEY_SPREAD = 73;
/** highlights.key.offset (radians) */
export const P_KEY_OFFSET = 74;
/** highlights.key.ycc.white */
export const P_KEY_WHITE = 75;
/** highlights.key.ycc.black */
export const P_KEY_BLACK = 76;
/** highlights.key.ycc.saturation */
export const P_KEY_SAT = 77;
/** highlights.key.ycc.dodgeFill r */
export const P_KEY_DODGE_R = 78;
/** highlights.key.ycc.dodgeFill g */
export const P_KEY_DODGE_G = 79;
/** highlights.key.ycc.dodgeFill b */
export const P_KEY_DODGE_B = 80;
/** highlights.key.ycc.dodgeFill a */
export const P_KEY_DODGE_A = 81;
/** highlights.key.ycc.normalFill r */
export const P_KEY_FILL_R = 82;
/** highlights.key.ycc.normalFill g */
export const P_KEY_FILL_G = 83;
/** highlights.key.ycc.normalFill b */
export const P_KEY_FILL_B = 84;
/** highlights.key.ycc.normalFill a */
export const P_KEY_FILL_A = 85;
/** highlights.fill.amount */
export const P_FILL_AMOUNT = 86;
/** highlights.fill.curvature */
export const P_FILL_CURVATURE = 87;
/** highlights.fill.height */
export const P_FILL_HEIGHT = 88;
/** highlights.fill.opacity */
export const P_FILL_OPACITY = 89;
/** highlights.fill.spread (radians) */
export const P_FILL_SPREAD = 90;
/** highlights.fill.ycc.white */
export const P_FILL_WHITE = 91;
/** highlights.fill.ycc.black */
export const P_FILL_BLACK = 92;
/** highlights.fill.ycc.saturation */
export const P_FILL_SAT = 93;
/** highlights.fill.ycc.dodgeFill r */
export const P_FILL_DODGE_R = 94;
/** highlights.fill.ycc.dodgeFill g */
export const P_FILL_DODGE_G = 95;
/** highlights.fill.ycc.dodgeFill b */
export const P_FILL_DODGE_B = 96;
/** highlights.fill.ycc.dodgeFill a */
export const P_FILL_DODGE_A = 97;
/** highlights.fill.ycc.normalFill r */
export const P_FILL_FILL_R = 98;
/** highlights.fill.ycc.normalFill g */
export const P_FILL_FILL_G = 99;
/** highlights.fill.ycc.normalFill b */
export const P_FILL_FILL_B = 100;
/** highlights.fill.ycc.normalFill a */
export const P_FILL_FILL_A = 101;
/** highlights.diffuse.amountScale */
export const P_DIFFUSE_AMOUNT = 102;
/** highlights.diffuse.heightScale */
export const P_DIFFUSE_HEIGHT = 103;
/** highlights.diffuse.spreadScale */
export const P_DIFFUSE_SPREAD = 104;
/** highlights.inset */
export const P_RIM_INSET = 105;
/** backdropLensing.aberrationAmount */
export const P_LENS_AMOUNT = 106;
/** backdropLensing.aberrationAngle (radians) */
export const P_LENS_ANGLE = 107;
/** backdropLensing.aberrationHeight */
export const P_LENS_HEIGHT = 108;
/** backdropLensing.aberrationInset */
export const P_LENS_INSET = 109;
/** backdropLensing.edgeDistances[0] */
export const P_LENS_D0 = 110;
/** backdropLensing.edgeDistances[1] */
export const P_LENS_D1 = 111;
/** backdropLensing.edgeOpacities[0] */
export const P_LENS_OP0 = 112;
/** backdropLensing.edgeOpacities[1] */
export const P_LENS_OP1 = 113;
/** backdropLensing.refractionAmount */
export const P_LENS_REFRACTION = 114;
/** backdropLensing.refractionHeight */
export const P_LENS_REFRACTION_HEIGHT = 115;
/** backdropLensing.refractionInset */
export const P_LENS_REFRACTION_INSET = 116;
/** derived.backdropMarginWidth */
export const P_MARGIN = 117;
/** Length of the parameter vector. */
export const P_COUNT = 118;
/** Bit i of word i >> 5: value i follows the smallest member of a union (the rest the largest one). */
export const P_NEAR = new Int32Array([49216, 0, 0, 1897472]);
